[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "henv"
version = "0.1.0"
description = "A lightweight local environment manager, similar to venv"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }

[project.scripts]
henv = "henv.cli:main"
